export const MAZE_CONFIG = {
  MIN_SIZE: 2,
  MAX_SIZE: 50,
  DEFAULT_SIZE: 15,

  INITIAL_TIME_SECONDS: 60,
  WARNING_TIME_THRESHOLD: 10,

  SCORE_BASE_MULTIPLIER: 10,

  STROKE_WEIGHT_DEFAULT: 10,
  STROKE_WEIGHT_DENSE: 10,
  DENSE_CELL_THRESHOLD: 35,

  BOUNDARY_BUFFER_MULTIPLIER: 2,
  MIN_CELL_OFFSET: 2,
  PLAYER_SIZE_DIVISOR: 3.5,
  MIN_PLAYER_SIZE: 3,

  TOUCH_SWIPE_THRESHOLD: 20,
} as const;